server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 118.178.59.191

management:
  endpoints:
    web:
      exposure:
        include: '*'