server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 118.178.59.191
    sentinel:
      transport:
        #配置sentinel dashboard地址（8080会监控本微服务8401）
        dashboard: localhost:8080
        #这个是和8080做交互的，就是我们在8080界面做配置，8080会把配置的东西发送给8719就是本springboot应用，然后sentinel才会生效
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true