
server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID,没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #使用9527端口访问则就相匹配，后面就会匹配到真实的8001端口
          uri: lb:http://cloud-payment-service #使用9527端口访问就会匹配成cloud-payment-service匹配后提供服务的路由地址 lb是实现自动负载均衡
          predicates:
            - Path=/payment/get/** #断言，路径如果是路径/payment/get则就相匹配（**表示任意参数），就可以去调用真的服务接口了
          #说变了就是uri协议host端口匹配，predicates路径匹配

        - id: payment_routh2 #路由的ID,没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #使用9527端口访问就会匹配成8001的路由地址
          uri: lb:http://cloud-payment-service #使用9527端口访问就会匹配成cloud-payment-service匹配后提供服务的路由地址 lb是实现自动负载均衡
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由**表示任意参数
            #- After=2020-10-26T14:52:45.904+08:00[Asia/Shanghai]  #这个时间点之后才有效
            #- Method=Get          #请求方法
            #- Query=username, \d+ #请求参数
            #- Cookie=username,lww #访问需要带cookie
            #- Header=head-username, \d+ #请求头要有head-username属性并且值为整数的正则表达式\d+ 数字
eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
