server:
  port: 2001

spring:
  application:
    name: seata-order-service

  cloud:
    nacos:
      discovery:
        server-addr: 118.178.59.191
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        #这里要和seata服务配置文件中的service中的vgroup_mapping.my_test_tx_group = "fsp_tx_group(与这里相对应)"
        tx-service-group: fsp_tx_group

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.178.59.191:3306/seata_order
    username: root
    password: woshimima

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
